name: Build (Pull Requests)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

env:
  GOPROXY: https://proxy.golang.org

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v5

      - uses: ./.github/workflows/composite-actions/lint

  unit-tests:
    needs: [lint]
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/workflows/composite-actions/unit-tests

  build:
    needs: [lint, unit-tests]
    runs-on: ubuntu-latest
    name: Build all platforms (darwin/amd64, darwin/arm64, linux/amd64)
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/composite-actions/build
        with:
          artifact-name: lok8s-binaries-pr
          checksum-name: lok8s-checksums-pr
          upload-artifacts: "false"

  build-linux-arm64:
    needs: [lint, unit-tests]
    runs-on: ubuntu-24.04-arm
    name: Build linux ARM64
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/composite-actions/build-linux-arm64
        with:
          artifact-name: lok8s-binaries-arm64-pr
          checksum-name: lok8s-checksums-arm64-pr
          upload-artifacts: "false"
